### ISSUE TITLE
missing version key for future Home Assistant Release

### ISSUE THREAD

**Issue by heinekmadsen** [geertsmichael/soundtouch#1]
Hi...
Just running through my log file from HA and i saw this:
![image](https://user-images.githubusercontent.com/48906528/114389753-affda480-9b95-11eb-8191-eb4f432d3b36.png)

Not sure how to fix this, but just an heads up :)

**Comment by KNXBroker** [comment]
@geertsmichael, seems that you are not maintaining this repository any more? I have created a fork https://github.com/KNXBroker/soundtouch and made it HA 2022.2 compatible again. 

I would be grateful if I could either contribute my changes to your repository - or - if you could link my repository. 

Best regards!

**Comment by scxs535** [comment]
@KNXBroker 
do you have this issue?
https://github.com/home-assistant/core/issues/61945
